spring:
  redis:
    database: 0
    host: 127.0.0.1
    password: 123
    port: 6379
    timeout: 3000       # 连接超时时间 单位 ms（毫秒）
    #    cluster:
    #      nodes: 10.3.1.4:7000,10.3.1.4:7001,...,10.3.1.4:7008
    jedis:
      pool:
        max-idle: 25    # 连接池中的最大空闲连接，默认值也是8
        min-idle: 10    # 连接池中的最小空闲连接，默认值也是0
        max-active: 50  # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
        max-wait: -1    # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出
